/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laberintoguia.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author emily
 */
public class GUIPerdio extends javax.swing.JFrame {

    /**
     * Creates new form GUIPerdio
     */
    public GUIPerdio() {
        initComponents();
    }
    
     public void escuchar (ActionListener controlador)
    {
        btnSiPerdio.addActionListener(controlador);
        btnNoPerdio.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNoPerdio = new javax.swing.JButton();
        btnSiPerdio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNoPerdio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnNo.png"))); // NOI18N
        btnNoPerdio.setBorderPainted(false);
        btnNoPerdio.setContentAreaFilled(false);
        btnNoPerdio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoPerdioActionPerformed(evt);
            }
        });
        getContentPane().add(btnNoPerdio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 150, 90));

        btnSiPerdio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSi.png"))); // NOI18N
        btnSiPerdio.setBorderPainted(false);
        btnSiPerdio.setContentAreaFilled(false);
        getContentPane().add(btnSiPerdio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPerdió.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 803, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoPerdioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoPerdioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoPerdioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPerdio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPerdio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPerdio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPerdio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPerdio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoPerdio;
    private javax.swing.JButton btnSiPerdio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
