/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laberintoguia.vista;


import java.awt.event.ActionListener;

/**
 *
 * @author emily
 */
public class GUIinstrucciones extends javax.swing.JFrame {

    /**
     * Creates new form GUIinstrucciones
     */
    public GUIinstrucciones() {
        initComponents();
       
    }
    
    public void escuchar (ActionListener controlador)
    {
        btnSalirInstrucciones.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalirInstrucciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalirInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSalir.png"))); // NOI18N
        btnSalirInstrucciones.setActionCommand("SalirIntrucciones");
        btnSalirInstrucciones.setBorderPainted(false);
        btnSalirInstrucciones.setContentAreaFilled(false);
        btnSalirInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 160, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instrucciones.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirInstruccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirInstruccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirInstrucciones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

